/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['@mixin navbar-theme ($theme) {\r\n  $primary: map-get($theme, primary);\r\n  app-navbar>nav {\r\n    background-color: mat-color($primary);\r\n    display: flex;\r\n    padding: 8px 16px;\r\n    text-transform: uppercase;\r\n  }\r\n}\r\n\r\nnav[_ngcontent-%COMP%] {\r\n  a {\r\n    &:last-child {\r\n      margin-left: auto;\r\n    }\r\n  }\r\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovTXlXb3JrL3BvcnRmb2xpby9zcmMvYXBwL2NvcmUvbmF2YmFyLmNvbXBvbmVudC9uYXZiYXIuY29tcG9uZW50LnNjc3Muc2hpbS5uZ3N0eWxlLnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovTXlXb3JrL3BvcnRmb2xpby9zcmMvYXBwL2NvcmUvbmF2YmFyLmNvbXBvbmVudC9uYXZiYXIuY29tcG9uZW50LnNjc3MiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7OyJ9
