/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = [''];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovTXlXb3JrL3BvcnRmb2xpby9zcmMvYXBwL3BhZ2Utbm90LWZvdW5kLmNvbXBvbmVudC9wYWdlLW5vdC1mb3VuZC5jb21wb25lbnQuc2Nzcy5zaGltLm5nc3R5bGUudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9NeVdvcmsvcG9ydGZvbGlvL3NyYy9hcHAvcGFnZS1ub3QtZm91bmQuY29tcG9uZW50L3BhZ2Utbm90LWZvdW5kLmNvbXBvbmVudC5zY3NzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7OzsifQ==
