/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './page-not-found.component.scss.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from '../../../app/page-not-found.component/page-not-found.component';
const styles_PageNotFoundComponent:any[] = [i0.styles];
export const RenderType_PageNotFoundComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_PageNotFoundComponent,data:{}});
export function View_PageNotFoundComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'h2',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i1.ɵted((null as any),['404 - Page not found'])),(_l()(),i1.ɵted((null as any),
      ['\n']))],(null as any),(null as any));
}
export function View_PageNotFoundComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'app-page-not-found',
      ([] as any[]),(null as any),(null as any),(null as any),View_PageNotFoundComponent_0,
      RenderType_PageNotFoundComponent)),i1.ɵdid(114688,(null as any),0,i2.PageNotFoundComponent,
      ([] as any[]),(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const PageNotFoundComponentNgFactory:i1.ComponentFactory<i2.PageNotFoundComponent> = i1.ɵccf('app-page-not-found',
    i2.PageNotFoundComponent,View_PageNotFoundComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovTXlXb3JrL3BvcnRmb2xpby9zcmMvYXBwL3BhZ2Utbm90LWZvdW5kLmNvbXBvbmVudC9wYWdlLW5vdC1mb3VuZC5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovTXlXb3JrL3BvcnRmb2xpby9zcmMvYXBwL3BhZ2Utbm90LWZvdW5kLmNvbXBvbmVudC9wYWdlLW5vdC1mb3VuZC5jb21wb25lbnQudHMiLCJuZzovLy9DOi9NeVdvcmsvcG9ydGZvbGlvL3NyYy9hcHAvcGFnZS1ub3QtZm91bmQuY29tcG9uZW50L3BhZ2Utbm90LWZvdW5kLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovTXlXb3JrL3BvcnRmb2xpby9zcmMvYXBwL3BhZ2Utbm90LWZvdW5kLmNvbXBvbmVudC9wYWdlLW5vdC1mb3VuZC5jb21wb25lbnQudHMuUGFnZU5vdEZvdW5kQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPGgyPjQwNCAtIFBhZ2Ugbm90IGZvdW5kPC9oMj5cclxuIiwiPGFwcC1wYWdlLW5vdC1mb3VuZD48L2FwcC1wYWdlLW5vdC1mb3VuZD4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7b0JDQUE7TUFBQSx3RUFBSTthQUFBLDBDQUF5QjtNQUFBOzs7b0JDQTdCO01BQUE7c0NBQUEsVUFBQTtNQUFBO0lBQUE7Ozs7In0=
