/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './app.component.scss.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from './core/navbar.component/navbar.component.ngfactory';
import * as i3 from '../../app/core/navbar.component/navbar.component';
import * as i4 from './core/primary-header.component/primary-header.component.ngfactory';
import * as i5 from '../../app/core/primary-header.component/primary-header.component';
import * as i6 from '@angular/router';
import * as i7 from '../../app/app.component';
const styles_AppComponent:any[] = [i0.styles];
export const RenderType_AppComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,styles:styles_AppComponent,
    data:{}});
export function View_AppComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),16,'div',[['class',
      'mat-app-background mat-typography']],(null as any),(null as any),(null as any),
      (null as any),(null as any))),(_l()(),i1.ɵted((null as any),['\n    '])),(_l()(),
      i1.ɵeld(0,(null as any),(null as any),7,'div',[['class','header']],(null as any),
          (null as any),(null as any),(null as any),(null as any))),(_l()(),i1.ɵted((null as any),
      ['\n        '])),(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'app-navbar',
      ([] as any[]),(null as any),(null as any),(null as any),i2.View_NavbarComponent_0,
      i2.RenderType_NavbarComponent)),i1.ɵdid(49152,(null as any),0,i3.NavbarComponent,
      ([] as any[]),(null as any),(null as any)),(_l()(),i1.ɵted((null as any),['\n        '])),
      (_l()(),i1.ɵeld(0,(null as any),(null as any),1,'app-primary-header',([] as any[]),
          (null as any),(null as any),(null as any),i4.View_PrimaryHeaderComponent_0,
          i4.RenderType_PrimaryHeaderComponent)),i1.ɵdid(114688,(null as any),0,i5.PrimaryHeaderComponent,
          [i6.ActivatedRoute,i6.Router],(null as any),(null as any)),(_l()(),i1.ɵted((null as any),
          ['\n    '])),(_l()(),i1.ɵted((null as any),['\n    '])),(_l()(),i1.ɵeld(0,
          (null as any),(null as any),4,'div',[['class','doc-wrapper']],(null as any),
          (null as any),(null as any),(null as any),(null as any))),(_l()(),i1.ɵted((null as any),
          ['\n        '])),(_l()(),i1.ɵeld(16777216,(null as any),(null as any),1,
          'router-outlet',([] as any[]),(null as any),(null as any),(null as any),
          (null as any),(null as any))),i1.ɵdid(212992,(null as any),0,i6.RouterOutlet,
          [i6.ChildrenOutletContexts,i1.ViewContainerRef,i1.ComponentFactoryResolver,
              [8,(null as any)],i1.ChangeDetectorRef],(null as any),(null as any)),
      (_l()(),i1.ɵted((null as any),['\n    '])),(_l()(),i1.ɵted((null as any),['\n'])),
      (_l()(),i1.ɵted((null as any),['\n']))],(_ck,_v) => {
    _ck(_v,8,0);
    _ck(_v,14,0);
  },(null as any));
}
export function View_AppComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'app-root',([] as any[]),
      (null as any),(null as any),(null as any),View_AppComponent_0,RenderType_AppComponent)),
      i1.ɵdid(114688,(null as any),0,i7.AppComponent,([] as any[]),(null as any),(null as any))],
      (_ck,_v) => {
        _ck(_v,1,0);
      },(null as any));
}
export const AppComponentNgFactory:i1.ComponentFactory<i7.AppComponent> = i1.ɵccf('app-root',
    i7.AppComponent,View_AppComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovTXlXb3JrL3BvcnRmb2xpby9zcmMvYXBwL2FwcC5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovTXlXb3JrL3BvcnRmb2xpby9zcmMvYXBwL2FwcC5jb21wb25lbnQudHMiLCJuZzovLy9DOi9NeVdvcmsvcG9ydGZvbGlvL3NyYy9hcHAvYXBwLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovTXlXb3JrL3BvcnRmb2xpby9zcmMvYXBwL2FwcC5jb21wb25lbnQudHMuQXBwQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPGRpdiBjbGFzcz1cIm1hdC1hcHAtYmFja2dyb3VuZCBtYXQtdHlwb2dyYXBoeVwiPlxyXG4gICAgPGRpdiBjbGFzcz1cImhlYWRlclwiPlxyXG4gICAgICAgIDxhcHAtbmF2YmFyPjwvYXBwLW5hdmJhcj5cclxuICAgICAgICA8YXBwLXByaW1hcnktaGVhZGVyPjwvYXBwLXByaW1hcnktaGVhZGVyPlxyXG4gICAgPC9kaXY+XHJcbiAgICA8ZGl2IGNsYXNzPVwiZG9jLXdyYXBwZXJcIj5cclxuICAgICAgICA8cm91dGVyLW91dGxldD48L3JvdXRlci1vdXRsZXQ+XHJcbiAgICA8L2Rpdj5cclxuPC9kaXY+XHJcbiIsIjxhcHAtcm9vdD48L2FwcC1yb290PiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O29CQ0FBO01BQUE7TUFBQSw4QkFBK0MsMkNBQzNDO2FBQUE7VUFBQSwwREFBb0I7TUFBQSxpQkFDaEI7TUFBQTttQ0FBQSxVQUFBO01BQUEsMkNBQXlCO01BQ3pCO1VBQUE7OENBQUEsVUFBQTtVQUFBLDJEQUF5QztVQUFBLGFBQ3ZDLDJDQUNOO1VBQUE7VUFBQSwwREFBeUI7VUFBQSxpQkFDckI7VUFBQTtVQUFBLHFDQUFBO1VBQUE7Y0FBQTtNQUErQiwyQ0FDN0I7TUFDSjtJQUxFO0lBR0E7Ozs7b0JDTlI7TUFBQTthQUFBOztRQUFBOzs7OyJ9
