/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './styles/mixins.scss.shim.ngstyle';
import * as i1 from './styles/variables.scss.shim.ngstyle';
export const styles:any[] = ['.header[_ngcontent-%COMP%] {\r\n  box-shadow: 0 2px 5px rgba(0, 0, 0, .26);\r\n  position: fixed;\r\n  width: 100%;\r\n  top: 0;\r\n}\r\n\r\n.doc-wrapper[_ngcontent-%COMP%] {\r\n  padding: 20px 70px;\r\n  display: block;\r\n  margin: 0 auto;\r\n}\r\n\r\nrouter-outlet[_ngcontent-%COMP%] {\r\n  max-width: 940px;\r\n}',
    i0.styles,i1.styles];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovTXlXb3JrL3BvcnRmb2xpby9zcmMvYXBwL2FwcC5jb21wb25lbnQuc2Nzcy5zaGltLm5nc3R5bGUudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9NeVdvcmsvcG9ydGZvbGlvL3NyYy9hcHAvYXBwLmNvbXBvbmVudC5zY3NzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7OzsifQ==
