/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './doc-viewer.component.scss.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from '../../../../../app/shared/components/doc-viewer.component/doc-viewer.component';
const styles_DocViewerComponent:any[] = [i0.styles];
export const RenderType_DocViewerComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_DocViewerComponent,data:{}});
export function View_DocViewerComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),4,'div',[['class',
      'doc-viewer-wrapper']],(null as any),(null as any),(null as any),(null as any),
      (null as any))),(_l()(),i1.ɵted((null as any),['\n    '])),(_l()(),i1.ɵeld(0,
      (null as any),(null as any),1,'div',[['class','doc-viewer-content']],(null as any),
      (null as any),(null as any),(null as any),(null as any))),(_l()(),i1.ɵted((null as any),
      ['\n    '])),(_l()(),i1.ɵted((null as any),['\n']))],(null as any),(null as any));
}
export function View_DocViewerComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'app-doc-viewer',
      ([] as any[]),(null as any),(null as any),(null as any),View_DocViewerComponent_0,
      RenderType_DocViewerComponent)),i1.ɵdid(114688,(null as any),0,i2.DocViewerComponent,
      ([] as any[]),(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const DocViewerComponentNgFactory:i1.ComponentFactory<i2.DocViewerComponent> = i1.ɵccf('app-doc-viewer',
    i2.DocViewerComponent,View_DocViewerComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovTXlXb3JrL3BvcnRmb2xpby9zcmMvYXBwL3NoYXJlZC9jb21wb25lbnRzL2RvYy12aWV3ZXIuY29tcG9uZW50L2RvYy12aWV3ZXIuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L015V29yay9wb3J0Zm9saW8vc3JjL2FwcC9zaGFyZWQvY29tcG9uZW50cy9kb2Mtdmlld2VyLmNvbXBvbmVudC9kb2Mtdmlld2VyLmNvbXBvbmVudC50cyIsIm5nOi8vL0M6L015V29yay9wb3J0Zm9saW8vc3JjL2FwcC9zaGFyZWQvY29tcG9uZW50cy9kb2Mtdmlld2VyLmNvbXBvbmVudC9kb2Mtdmlld2VyLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovTXlXb3JrL3BvcnRmb2xpby9zcmMvYXBwL3NoYXJlZC9jb21wb25lbnRzL2RvYy12aWV3ZXIuY29tcG9uZW50L2RvYy12aWV3ZXIuY29tcG9uZW50LnRzLkRvY1ZpZXdlckNvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxkaXYgY2xhc3M9J2RvYy12aWV3ZXItd3JhcHBlcic+XHJcbiAgICA8ZGl2IGNsYXNzPVwiZG9jLXZpZXdlci1jb250ZW50XCI+XHJcbiAgICA8L2Rpdj5cclxuPC9kaXY+IiwiPGFwcC1kb2Mtdmlld2VyPjwvYXBwLWRvYy12aWV3ZXI+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7O29CQ0FBO01BQUE7TUFBQSxnQkFBZ0MsMkNBQzVCO01BQUE7TUFBQSwwREFBZ0M7TUFBQSxhQUMxQjs7O29CQ0ZWO01BQUE7bUNBQUEsVUFBQTtNQUFBO0lBQUE7Ozs7In0=
