/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['@mixin primary-header-theme ($theme) {\r\n  $primary: map-get($theme, primary);\r\n  app-primary-header>div {\r\n    background-color: mat-color($primary);\r\n    margin: 0;\r\n    padding: 30px 50px 50px 50px;\r\n  }\r\n}\r\n\r\napp-primary-header[_ngcontent-%COMP%] {\r\n  .primary-header-wrapper {\r\n    height: 40px;\r\n    .mat-display-1 {\r\n      margin: 0;\r\n    }\r\n  }\r\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovTXlXb3JrL3BvcnRmb2xpby9zcmMvYXBwL2NvcmUvcHJpbWFyeS1oZWFkZXIuY29tcG9uZW50L3ByaW1hcnktaGVhZGVyLmNvbXBvbmVudC5zY3NzLnNoaW0ubmdzdHlsZS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L015V29yay9wb3J0Zm9saW8vc3JjL2FwcC9jb3JlL3ByaW1hcnktaGVhZGVyLmNvbXBvbmVudC9wcmltYXJ5LWhlYWRlci5jb21wb25lbnQuc2NzcyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7In0=
