/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './primary-header.component.scss.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from '../../../../app/core/primary-header.component/primary-header.component';
import * as i3 from '@angular/router';
const styles_PrimaryHeaderComponent:any[] = [i0.styles];
export const RenderType_PrimaryHeaderComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_PrimaryHeaderComponent,data:{}});
export function View_PrimaryHeaderComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),4,'div',[['class',
      'primary-header-wrapper']],(null as any),(null as any),(null as any),(null as any),
      (null as any))),(_l()(),i1.ɵted((null as any),['\n    '])),(_l()(),i1.ɵeld(0,
      (null as any),(null as any),1,'h1',[['class','mat-display-1']],(null as any),
      (null as any),(null as any),(null as any),(null as any))),(_l()(),i1.ɵted((null as any),
      ['',''])),(_l()(),i1.ɵted((null as any),['\n'])),(_l()(),i1.ɵted((null as any),
      ['\n']))],(null as any),(_ck,_v) => {
    var _co:i2.PrimaryHeaderComponent = _v.component;
    const currVal_0:any = _co.title;
    _ck(_v,3,0,currVal_0);
  });
}
export function View_PrimaryHeaderComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'app-primary-header',
      ([] as any[]),(null as any),(null as any),(null as any),View_PrimaryHeaderComponent_0,
      RenderType_PrimaryHeaderComponent)),i1.ɵdid(114688,(null as any),0,i2.PrimaryHeaderComponent,
      [i3.ActivatedRoute,i3.Router],(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const PrimaryHeaderComponentNgFactory:i1.ComponentFactory<i2.PrimaryHeaderComponent> = i1.ɵccf('app-primary-header',
    i2.PrimaryHeaderComponent,View_PrimaryHeaderComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovTXlXb3JrL3BvcnRmb2xpby9zcmMvYXBwL2NvcmUvcHJpbWFyeS1oZWFkZXIuY29tcG9uZW50L3ByaW1hcnktaGVhZGVyLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9NeVdvcmsvcG9ydGZvbGlvL3NyYy9hcHAvY29yZS9wcmltYXJ5LWhlYWRlci5jb21wb25lbnQvcHJpbWFyeS1oZWFkZXIuY29tcG9uZW50LnRzIiwibmc6Ly8vQzovTXlXb3JrL3BvcnRmb2xpby9zcmMvYXBwL2NvcmUvcHJpbWFyeS1oZWFkZXIuY29tcG9uZW50L3ByaW1hcnktaGVhZGVyLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovTXlXb3JrL3BvcnRmb2xpby9zcmMvYXBwL2NvcmUvcHJpbWFyeS1oZWFkZXIuY29tcG9uZW50L3ByaW1hcnktaGVhZGVyLmNvbXBvbmVudC50cy5QcmltYXJ5SGVhZGVyQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPGRpdiBjbGFzcz1cInByaW1hcnktaGVhZGVyLXdyYXBwZXJcIj5cclxuICAgIDxoMSBjbGFzcz1cIm1hdC1kaXNwbGF5LTFcIj57e3RpdGxlfX08L2gxPlxyXG48L2Rpdj5cclxuIiwiPGFwcC1wcmltYXJ5LWhlYWRlcj48L2FwcC1wcmltYXJ5LWhlYWRlcj4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7O29CQ0FBO01BQUE7TUFBQSxnQkFBb0MsMkNBQ2hDO01BQUE7TUFBQSwwREFBMEI7TUFBQSxVQUFjLHVDQUN0QztNQUFBOztJQUR3QjtJQUFBOzs7O29CQ0Q5QjtNQUFBO3VDQUFBLFVBQUE7TUFBQTtJQUFBOzs7OyJ9
