/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../app/core/core.module';
import * as i2 from '@angular/common';
import * as i3 from '@angular/cdk';
import * as i4 from '@angular/platform-browser';
import * as i5 from '@angular/material';
import * as i6 from '@angular/http';
import * as i7 from '../../../app/shared/shared.module';
import * as i8 from '@angular/router';
export const CoreModuleNgFactory:i0.NgModuleFactory<i1.CoreModule> = i0.ɵcmf(i1.CoreModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,([] as any[])],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(4608,
          i2.NgLocalization,i2.NgLocaleLocalization,[i0.LOCALE_ID]),i0.ɵmpd(6144,i3.DIR_DOCUMENT,
          (null as any),[i4.DOCUMENT]),i0.ɵmpd(4608,i3.Directionality,i3.Directionality,
          [[2,i3.DIR_DOCUMENT]]),i0.ɵmpd(5120,i5.MdIconRegistry,i5.ICON_REGISTRY_PROVIDER_FACTORY,
          [[3,i5.MdIconRegistry],[2,i6.Http],i4.DomSanitizer]),i0.ɵmpd(4608,i3.Platform,
          i3.Platform,([] as any[])),i0.ɵmpd(5120,i5.ScrollDispatcher,i5.ɵe,[[3,i5.ScrollDispatcher],
          i0.NgZone,i3.Platform]),i0.ɵmpd(5120,i5.ViewportRuler,i5.ɵc,[[3,i5.ViewportRuler],
          i5.ScrollDispatcher]),i0.ɵmpd(4608,i5.ScrollStrategyOptions,i5.ScrollStrategyOptions,
          [i5.ScrollDispatcher,i5.ViewportRuler]),i0.ɵmpd(5120,i5.FocusOriginMonitor,
          i5.FOCUS_ORIGIN_MONITOR_PROVIDER_FACTORY,[[3,i5.FocusOriginMonitor],i0.NgZone,
              i3.Platform]),i0.ɵmpd(512,i2.CommonModule,i2.CommonModule,([] as any[])),
          i0.ɵmpd(512,i5.CompatibilityModule,i5.CompatibilityModule,([] as any[])),
          i0.ɵmpd(512,i3.BidiModule,i3.BidiModule,([] as any[])),i0.ɵmpd(256,i5.MATERIAL_SANITY_CHECKS,
              true,([] as any[])),i0.ɵmpd(512,i5.MdCommonModule,i5.MdCommonModule,
              [[2,i4.DOCUMENT],[2,i5.MATERIAL_SANITY_CHECKS]]),i0.ɵmpd(512,i5.MdIconModule,
              i5.MdIconModule,([] as any[])),i0.ɵmpd(512,i3.PlatformModule,i3.PlatformModule,
              ([] as any[])),i0.ɵmpd(512,i5.ScrollDispatchModule,i5.ScrollDispatchModule,
              ([] as any[])),i0.ɵmpd(512,i5.MdRippleModule,i5.MdRippleModule,([] as any[])),
          i0.ɵmpd(512,i5.StyleModule,i5.StyleModule,([] as any[])),i0.ɵmpd(512,i5.MdButtonModule,
              i5.MdButtonModule,([] as any[])),i0.ɵmpd(512,i5.MdToolbarModule,i5.MdToolbarModule,
              ([] as any[])),i0.ɵmpd(512,i7.SharedModule,i7.SharedModule,([] as any[])),
          i0.ɵmpd(512,i8.RouterModule,i8.RouterModule,[[2,i8.ɵa],[2,i8.Router]]),i0.ɵmpd(512,
              i1.CoreModule,i1.CoreModule,[[3,i1.CoreModule]])]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovTXlXb3JrL3BvcnRmb2xpby9zcmMvYXBwL2NvcmUvY29yZS5tb2R1bGUubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovTXlXb3JrL3BvcnRmb2xpby9zcmMvYXBwL2NvcmUvY29yZS5tb2R1bGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
