/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../app/aboutme/aboutme-routing.module';
import * as i2 from './aboutme.component.ngfactory';
import * as i3 from '@angular/router';
import * as i4 from '../../../app/aboutme/aboutme.component';
export const AboutMeRoutingModuleNgFactory:i0.NgModuleFactory<i1.AboutMeRoutingModule> = i0.ɵcmf(i1.AboutMeRoutingModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i2.AboutMeComponentNgFactory]],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),
          i0.ɵmpd(512,i3.RouterModule,i3.RouterModule,[[2,i3.ɵa],[2,i3.Router]]),i0.ɵmpd(512,
              i1.AboutMeRoutingModule,i1.AboutMeRoutingModule,([] as any[])),i0.ɵmpd(1024,
              i3.ROUTES,() => {
                return [[{path:'aboutme',component:i4.AboutMeComponent,data:{title:'About Me'}}]];
              },([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovTXlXb3JrL3BvcnRmb2xpby9zcmMvYXBwL2Fib3V0bWUvYWJvdXRtZS1yb3V0aW5nLm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9NeVdvcmsvcG9ydGZvbGlvL3NyYy9hcHAvYWJvdXRtZS9hYm91dG1lLXJvdXRpbmcubW9kdWxlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
