/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './aboutme.component.scss.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from '../../../app/aboutme/aboutme.component';
const styles_AboutMeComponent:any[] = [i0.styles];
export const RenderType_AboutMeComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_AboutMeComponent,data:{}});
export function View_AboutMeComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵted((null as any),['aboutme']))],(null as any),(null as any));
}
export function View_AboutMeComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'app-aboutme',
      ([] as any[]),(null as any),(null as any),(null as any),View_AboutMeComponent_0,
      RenderType_AboutMeComponent)),i1.ɵdid(49152,(null as any),0,i2.AboutMeComponent,
      ([] as any[]),(null as any),(null as any))],(null as any),(null as any));
}
export const AboutMeComponentNgFactory:i1.ComponentFactory<i2.AboutMeComponent> = i1.ɵccf('app-aboutme',
    i2.AboutMeComponent,View_AboutMeComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovTXlXb3JrL3BvcnRmb2xpby9zcmMvYXBwL2Fib3V0bWUvYWJvdXRtZS5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovTXlXb3JrL3BvcnRmb2xpby9zcmMvYXBwL2Fib3V0bWUvYWJvdXRtZS5jb21wb25lbnQudHMiLCJuZzovLy9DOi9NeVdvcmsvcG9ydGZvbGlvL3NyYy9hcHAvYWJvdXRtZS9hYm91dG1lLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovTXlXb3JrL3BvcnRmb2xpby9zcmMvYXBwL2Fib3V0bWUvYWJvdXRtZS5jb21wb25lbnQudHMuQWJvdXRNZUNvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsImFib3V0bWUiLCI8YXBwLWFib3V0bWU+PC9hcHAtYWJvdXRtZT4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7b0JDQUE7OztvQkNBQTtNQUFBO2lDQUFBLFVBQUE7TUFBQTs7OyJ9
