/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../app/aboutme/aboutme.module';
import * as i2 from './aboutme.component.ngfactory';
import * as i3 from '@angular/common';
import * as i4 from '@angular/cdk';
import * as i5 from '@angular/platform-browser';
import * as i6 from '@angular/material';
import * as i7 from '@angular/http';
import * as i8 from '../../../app/shared/shared.module';
import * as i9 from '@angular/router';
import * as i10 from '../../../app/aboutme/aboutme-routing.module';
import * as i11 from '../../../app/aboutme/aboutme.component';
export const AboutMeModuleNgFactory:i0.NgModuleFactory<i1.AboutMeModule> = i0.ɵcmf(i1.AboutMeModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i2.AboutMeComponentNgFactory]],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),
          i0.ɵmpd(4608,i3.NgLocalization,i3.NgLocaleLocalization,[i0.LOCALE_ID]),i0.ɵmpd(6144,
              i4.DIR_DOCUMENT,(null as any),[i5.DOCUMENT]),i0.ɵmpd(4608,i4.Directionality,
              i4.Directionality,[[2,i4.DIR_DOCUMENT]]),i0.ɵmpd(5120,i6.MdIconRegistry,
              i6.ICON_REGISTRY_PROVIDER_FACTORY,[[3,i6.MdIconRegistry],[2,i7.Http],
                  i5.DomSanitizer]),i0.ɵmpd(4608,i4.Platform,i4.Platform,([] as any[])),
          i0.ɵmpd(5120,i6.ScrollDispatcher,i6.ɵe,[[3,i6.ScrollDispatcher],i0.NgZone,
              i4.Platform]),i0.ɵmpd(5120,i6.ViewportRuler,i6.ɵc,[[3,i6.ViewportRuler],
              i6.ScrollDispatcher]),i0.ɵmpd(4608,i6.ScrollStrategyOptions,i6.ScrollStrategyOptions,
              [i6.ScrollDispatcher,i6.ViewportRuler]),i0.ɵmpd(5120,i6.FocusOriginMonitor,
              i6.FOCUS_ORIGIN_MONITOR_PROVIDER_FACTORY,[[3,i6.FocusOriginMonitor],
                  i0.NgZone,i4.Platform]),i0.ɵmpd(512,i3.CommonModule,i3.CommonModule,
              ([] as any[])),i0.ɵmpd(512,i6.CompatibilityModule,i6.CompatibilityModule,
              ([] as any[])),i0.ɵmpd(512,i4.BidiModule,i4.BidiModule,([] as any[])),
          i0.ɵmpd(256,i6.MATERIAL_SANITY_CHECKS,true,([] as any[])),i0.ɵmpd(512,i6.MdCommonModule,
              i6.MdCommonModule,[[2,i5.DOCUMENT],[2,i6.MATERIAL_SANITY_CHECKS]]),i0.ɵmpd(512,
              i6.MdIconModule,i6.MdIconModule,([] as any[])),i0.ɵmpd(512,i4.PlatformModule,
              i4.PlatformModule,([] as any[])),i0.ɵmpd(512,i6.ScrollDispatchModule,
              i6.ScrollDispatchModule,([] as any[])),i0.ɵmpd(512,i6.MdRippleModule,
              i6.MdRippleModule,([] as any[])),i0.ɵmpd(512,i6.StyleModule,i6.StyleModule,
              ([] as any[])),i0.ɵmpd(512,i6.MdButtonModule,i6.MdButtonModule,([] as any[])),
          i0.ɵmpd(512,i6.MdToolbarModule,i6.MdToolbarModule,([] as any[])),i0.ɵmpd(512,
              i8.SharedModule,i8.SharedModule,([] as any[])),i0.ɵmpd(512,i9.RouterModule,
              i9.RouterModule,[[2,i9.ɵa],[2,i9.Router]]),i0.ɵmpd(512,i10.AboutMeRoutingModule,
              i10.AboutMeRoutingModule,([] as any[])),i0.ɵmpd(512,i1.AboutMeModule,
              i1.AboutMeModule,([] as any[])),i0.ɵmpd(1024,i9.ROUTES,() => {
            return [[{path:'aboutme',component:i11.AboutMeComponent,data:{title:'About Me'}}]];
          },([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovTXlXb3JrL3BvcnRmb2xpby9zcmMvYXBwL2Fib3V0bWUvYWJvdXRtZS5tb2R1bGUubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovTXlXb3JrL3BvcnRmb2xpby9zcmMvYXBwL2Fib3V0bWUvYWJvdXRtZS5tb2R1bGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
