/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '../../node_modules/@angular/material/_theming.scss.shim.ngstyle';
export const styles:any[] = ['@mixin font-stack {\r\n  font-family: \'Roboto\', \'Noto Sans\', sans-serif;\r\n}\r\n\r\n@mixin electron-sun-theme($theme) {\r\n  // Extract whichever individual palettes you need from the theme.\r\n  $primary: map-get($theme, primary);\r\n  $accent: map-get($theme, accent); // Use mat-color to extract individual colors from a palette as necessary.\r\n  .electron-sun {\r\n    background-color: mat-color($primary);\r\n    border-color: mat-color($accent, A400);\r\n  }\r\n}',
    i0.styles];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovTXlXb3JrL3BvcnRmb2xpby9zcmMvYXBwL3N0eWxlcy9taXhpbnMuc2Nzcy5zaGltLm5nc3R5bGUudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9NeVdvcmsvcG9ydGZvbGlvL3NyYy9hcHAvc3R5bGVzL21peGlucy5zY3NzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7OyJ9
