/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['//[_ngcontent-%COMP%]   All[_ngcontent-%COMP%]   variables[_ngcontent-%COMP%]   should[_ngcontent-%COMP%]   be[_ngcontent-%COMP%]   in[_ngcontent-%COMP%]   here[_ngcontent-%COMP%]   then[_ngcontent-%COMP%]   imported[_ngcontent-%COMP%]   to[_ngcontent-%COMP%]   other[_ngcontent-%COMP%]   files\r\n$fa-font-path[_ngcontent-%COMP%]:   \'[_ngcontent-%COMP%] ~ font-awesome/fonts\'[_ngcontent-%COMP%];'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovTXlXb3JrL3BvcnRmb2xpby9zcmMvYXBwL3N0eWxlcy92YXJpYWJsZXMuc2Nzcy5zaGltLm5nc3R5bGUudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9NeVdvcmsvcG9ydGZvbGlvL3NyYy9hcHAvc3R5bGVzL3ZhcmlhYmxlcy5zY3NzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7OzsifQ==
